apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sink.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sink.name" . }}
    helm.sh/chart: {{ include "sink.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: vfirewall
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sink.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: vFirewall
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sink.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: vFirewall
        context: darkstat
      #annotations:
       # k8s.v1.cni.cncf.io/networks: '[{ "name": "$ovn_multus_network_name"}]'
        #ovnNetwork: '[
           # { "name": "$protected_private_net", "ipAddress": "$vsn_private_ip_0", "interface": "eth1", "defaultGateway": "false" },
           # { "name": "$onap_private_net", "ipAddress": "$vsn_private_ip_1", "interface": "eth2" , "defaultGateway": "false"}
        #]'
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          stdin: true
          securityContext:
            privileged: true
       # - name: darkstat
         # image: electrocucaracha/darkstat
         # imagePullPolicy: IfNotPresent
         # tty: true
         # stdin: true
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
